### ISSUE TITLE
Async Smile streaming support

### ISSUE THREAD

**Issue by sdeleuze** [FasterXML/jackson-dataformats-binary#127]
As part of [SPR-16151](https://jira.spring.io/browse/SPR-16151) and due to various users asking such support, we try to support Smile Async streaming in the upcoming Spring Framework 5.0.3, in a similar fashion we currently support JSON Async streaming.

I have done [various changes](https://github.com/sdeleuze/spring-framework/commit/SPR-16151) to support that, but my [integration tests](https://github.com/sdeleuze/spring-framework/blob/1d89a7f10bc8a107770f220c3a218b7d53d9730f/spring-webflux/src/test/java/org/springframework/web/reactive/result/method/annotation/JacksonStreamingIntegrationTests.java) with serialization/deserialization of 2 POJOs generates the following error:

`JSON: com.fasterxml.jackson.core.JsonParseException: Still have 21 undecoded bytes, should not call 'feedInput' at [Source: UNKNOWN; line: -1, column: 18]`

Data are concatenated without separator. 

Could you please check if this use case is currently supported, and if not support it?

**Comment by cowtowncoder** [comment]
Thanks, hope to look into this soon. I can first verify if this is tested or not; and if not, try to think of what the conceptual limitations might be (if any).

**Comment by sdeleuze** [comment]
Hey, any chance to have a look on this one in order to allow us to support Smile streaming in our upcoming 5.0.4 release expected on February 15th?

**Comment by cowtowncoder** [comment]
@sdeleuze haven't had a chance, but should have time week. Thanks for reminder.
I am planning on getting `2.9.4` release out sometime in January, due to some important (some for unexpected backwards compatibility issues, others for minor improvements wrt security handling for CVEs). So evaluating this should occur before that release.

**Comment by sdeleuze** [comment]
Thanks for the heads up.

**Comment by cowtowncoder** [comment]
I guess it would be really useful if there was a bit more isolated test, basically taking active calls into a unit test to show the problem. I assume that things work with both json and smile with regular blocking i/o, and individual objects via async for both as well. But that sequence of multiple object not so much with Smile.

**Comment by sdeleuze** [comment]
Please find a minimal repro use case in [this repository](https://github.com/sdeleuze/smile-streaming-issue). The [same test](https://github.com/sdeleuze/smile-streaming-issue/blob/master/src/test/java/StreamingTests.java) works with JSON but fails with Smile.

**Comment by cowtowncoder** [comment]
@sdeleuze Ah. I may know what is going on here. Brief version is that between Smile documents -- ones separated by header bytes and/or end marker, will return `null` token to indicate end of document. This does NOT necessarily indicate end of the whole stream, but rather that there is document boundary. To test if stream is done there are couple of ways; either getting another `null`, or, perhaps better, see if `parser.isClosed()` returns `true`. Or best maybe, `needMoreInput` (of `NonBlockingInputFeeder`) which indicates there is content to decode.
JSON, on the other hand, has no means for indicating document boundaries.

It is also possible, actually, to create Smile document "streams" without boundaries, if neither header nor end-marker is output. Such content would be exposed without intervening `null` tokens.

I am not sure what to think of this discrepancy: it is not ideal, obviously, but at the same time it does reflect actual difference between formats, as Smile has bit more metadata.
But in practical terms I think behavior can not be changed since this is part of API at this point -- as far as I can see this is not special for async API but would work same way on blocking API too.

Does this make sense?

**Comment by sdeleuze** [comment]
Yes that makes sense, thank for your guidance, I will update our implementation accordingly. I will close this issue after checking it works as expected with `parser.isClosed()` or `needMoreInput`.

**Comment by cowtowncoder** [comment]
@sdeleuze Thanks. Good catch, sorry it took so long for me to take a look. Good thing is that there was a test for root value handling, wrt separate documents. I may need to additionally consider use with the alternative of appending root-level values without closing stream (or, disabling start and end marker), which is represented differently but should still work without exceptions or failures (but omitting `null` marker in stream).

**Comment by sdeleuze** [comment]
FYI it works only when checking double `null`, other methods don't work.

**Comment by cowtowncoder** [comment]
@sdeleuze Ok. Yeah, probably `isClosed()` can't work with async the same way, without caller actually indicating "no more input" at point where `needsMoreInput()` would be `true`.

The intended logic is, I think, that `needsMoreInput()` only returns `true` after consuming all input being given. So if this is the case (returns `true`) AND there is no more input to feed, then there can not be more to read. But double-null is probably the best way at this point, simplest, should work.

**Comment by sdeleuze** [comment]
Yes I chose the double-null path, thanks for your feedback, Smile streaming will be supported in Spring Framework 5.0.4.

**Comment by cowtowncoder** [comment]
Excellent, I saw the announcement. This is great, thank you!
