### ISSUE TITLE
Decimal support in Avro Schemas

### ISSUE THREAD

**Issue by holub** [FasterXML/jackson-dataformats-binary#25]
Previously Avro didn't have direct support for Decimal types like BigDecimal in Java. Now it has: [Decimal](https://avro.apache.org/docs/1.8.1/spec.html#Decimal). That means the current implementation which use "double" as a replacement for decimal can be improved.

**Comment by cowtowncoder** [comment]
If anyone wants to take a stab for both serialization and deserialization, I can merge it.

I can't quite tell from description exactly how logical types should work so some investigation would be needed to figure out the whole system. There seem to be other logical types that could be supported as well.

**Comment by cowtowncoder** [comment]
FWTW, there has been lots of recent activity wrt Avro module, and I think `BigDecimal` values may now be  handled as Strings. I think this isn't 100% what was asked here but thought I'll mention as it may be relevant for further improvements.

**Comment by baharclerode** [comment]
Correct, in master `BigDecimal` is now correctly handled in a manner that is consistent with the avro reference implementation and fully preserves all precision.

Because `BigDecimal` is dynamic precision and the avro logical `Decimal` type is fixed precision, I would not generate schemas with logical `Decimal` fields for java's `BigDecimal`; However, the `NonBSGenericDatumWriter` could be updated such that Jackson is supported writing a `BigDecimal` into a logical `Decimal` field, assuming you have a hand-generated schema or used the `@AvroSchema` annotation. (It already coerces `BigDecimals` into a `double` if the field schema is `DOUBLE` instead of `STRING` to preserve compatibility with previously-generated schemas)
