### ISSUE TITLE
Serialization of multiple objects (`SequenceWriter`)

### ISSUE THREAD

**Issue by tomvandenberge** [FasterXML/jackson-dataformats-binary#35]
A common use case with Avro is to serialize multiple objects to a single file, and to deserialize multiple objects from a single file. This is done using DataFileWriter and DataFileReader. The file contains a single schema for all objects.

Would it be possible to do this with jackson-dataformat-avro?

Regards,
Tom

**Comment by cowtowncoder** [comment]
I haven't tested this, but in theory it should be supportable -- many other formats support multiple root-level objects, so from API perspective should be fine.
So just need to verify, and possible enhance.

One related note however: currently module only supports "raw" content, that is, no schema as pre-amble. There's another issue filed for that. Two features obviously should co-exist if so, so that only one schema instance should be within filed.

**Comment by cowtowncoder** [comment]
Implemented for 2.8.7 (and even backported 2.7.9 if that gets released)
