### ISSUE TITLE
Missing license file in Maven package for newer versions

### ISSUE THREAD

**Issue by desombre** [FasterXML/jackson-dataformats-binary#354]
The license file is missing in newer versions of the Maven packages source code. see: https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.14.2/ -> jackson-dataformat-cbor-2.14.2-sources.jar
In older versions e.g. 2.6.7 it was included.

**Comment by cowtowncoder** [comment]
Hmmh. Odd, I do not recall this being done on purpose. But looking quickly at repo, it looks like LICENSE would not only be missing from source jars but also binary ones. I wonder if this has been the case since 2.10 when multiple individual repositories were merged; addition of another level may have made parent-level `LICENSE` not found by sub-modules.

Anyway: need to make this work. Thank you for reporting the issue, @desombre !

**Comment by cowtowncoder** [comment]
Fixed this for all dataformat modules (here and otherwise), backporting into 2.12 onwards (in off-chance there might be micro-patches or something). But will be included in `2.14.3` and `2.15.0` when those get released.
