### ISSUE TITLE
[AVRO] 2 fields in schema for single property when getter and setter contain property name in capitals. 

### ISSUE THREAD

**Issue by MichalFoksa** [FasterXML/jackson-dataformats-binary#500]
Example Java class has a single property called PIN annotated with `@JsonProperty(value = "PIN")` plus getter and setter contain property name in capitals. 

```
@JsonProperty(value = "PIN")
private String PIN;
public String getPIN() ...
public void setPIN(String PIN) ...
```
I expect single field, `PIN`, in generated schema, however it contains two fields: `PIN` and `pin`.

Avro schema:
```
{
  "type" : "record",
  "name" : "UppercaseJsoPropertyPlusUppercaseGetterAndSetter",
  "namespace" : "xyz",
  "fields" : [ {
    "name" : "PIN",
    "type" : [ "null", "string" ]
  }, {
    "name" : "pin",
    "type" : [ "null", "string" ]
  } ]
}
```

I guess it is a bit edge case bug, or is it even a bug?

Test:
```
public static class UppercaseJsoPropertyPlusUppercaseGetterAndSetter {
    @JsonProperty(value = "PIN")
    private String PIN;

    public String getPIN() {
        return PIN;
    }

    public void setPIN(String PIN) {
        this.PIN = PIN;
    }
}

@Test
public void testSchemaCreation() throws JsonMappingException {
    // GIVEN
    AvroMapper mapper = AvroMapper.builder().build();

    // WHEN
    Schema actualSchema = mapper.schemaFor(UppercaseJsoPropertyPlusUppercaseGetterAndSetter.class)
            .getAvroSchema();

    System.out.printf("%s schema:\n%s",
            UppercaseJsoPropertyPlusUppercaseGetterAndSetter.class.getName(), actualSchema.toString(true));

    // THEN
    assertThat(actualSchema.getField("PIN")).isNotNull();
    // pin field should not be in Avro schema
    assertThat(actualSchema.getField("pin")).isNull();  // test fails here
}
```

**Comment by cowtowncoder** [comment]
This is more generic databind property introspection question, but it's a... feature of the way things work: implicit name detection

* Exposes field names as is (like `"PIN"`)
* Uses heuristics defaulting to "camel-case" to extract property name from getters/setters; in case of `getPIN()` resulting in `pin`

So by default, names would be different inferring 2 separate properties.

But the logic does unify things when explicit names are used, so you will need to make sure annotate either getter or setter and NOT field (field already has name you want). If you move `@JsonProperty("PIN")` to `getPIN()` (or `setPIN()`), things should work as expected.
This because annotations are merged across accessors, as long as names are linked.

Generally, unless you really want to expose access to field, annotating fields is less commonly used or useful than that of getter (or setter if you prefer).

FWTW we have thought about possibly allowing case-insensitive matching, to help with use case like this. But that has not been implemented -- it would be possible to tackle, given that we just very recently rewrote Property Introspection (to be included in 2.18.0) -- but not trivial to do.

In the meantime I would recommend moving `@JsonProperty` annotation to getter; either for affected cases (ones with property name starting with capital-case name), or for convenience all of them.

**Comment by MichalFoksa** [comment]
That code construct is a result of openapi generator when field name `PIN`.

Thank you for clarification. I can deal with it.

**Comment by cowtowncoder** [comment]
Ok, sounds good. This is bit of a known challenge with acronym-based fields, for which there is no good solution, yet. Glad that you can work around it.
