### ISSUE TITLE
[smile] jackson-dataformat-smile 2.8.7 throwing NoSuchMethodError when trying to write POJO as Bytes

### ISSUE THREAD

**Issue by smparekh** [FasterXML/jackson-dataformats-binary#70]
`
2017-03-31 17:35:30,470 (857753712@qtp-1838151277-0) [ERROR: Slf4jLog] Error for /
java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.smile.SmileFactory._decorate(Ljava/io/OutputStream;Lcom/fasterxml/jackson/core/io/IOContext;)Ljava/io/OutputStream;
	at com.fasterxml.jackson.dataformat.smile.SmileFactory.createGenerator(SmileFactory.java:351)
	at com.fasterxml.jackson.dataformat.smile.SmileFactory.createGenerator(SmileFactory.java:27)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:2299)
`

I have made sure to standardize the version of jackson-annotations, jackson-core, jackson-databind and jackson-dataformat-smile in my project.

**Comment by cowtowncoder** [comment]
@smparekh I understand that you have standardized versions (which is good), but I do think that somewhere in classpath you have old version of `jackson-core`: perhaps a duplicate. Method in question was added in `2.4`, so it would be version 2.3 or earlier (2.0, 2.1, 2.2).
This because compiler would not produce such output, and this is linker error, occurring during class loading.

**Comment by cowtowncoder** [comment]
I think this has to be version incompatibility between jars in classpath -- I can not see it as anything that project itself can do much about.

**Comment by smparekh** [comment]
Yup, the container running the jar didn't respect the newer version (included in the flume source as a dependency) as it was using the older version that was included in flume classpath. Basically means I can't use smile but it is not a bug with Jackson itself.
