### ISSUE TITLE
[Avro] AvroMapper with Map throwing UnsupportedOperationException

### ISSUE THREAD

**Issue by coder-hub** [FasterXML/jackson-dataformats-binary#98]
AvroMapper's schemaFor method throws UnsupportedOperationException when passing Map or HashMap however it works fine for POJO's with Map as a member. 

Following code throws exception during schemaFor method call:

```java
AvroMapper mapper = new AvroMapper();
AvroSchema avroSchema = avroMapper.schemaFor(map.getClass());
mapper.writer(avroSchema).writeValueAsBytes(map);
```

Following code doesn't throw exception:

```java
AvroMapper mapper = new AvroMapper(); 
AvroSchema avroSchema = avroMapper.schemaFor(pojo.getClass());
mapper.writer(avroSchema).writeValueAsBytes(pojo);

class Pojo {
  public Map<String, String> map;
}
```

**Comment by cowtowncoder** [comment]
qq: which version(s)?

**Comment by coder-hub** [comment]
I tried with multiple versions - 2.8.1 and 2.8.7. Thanks.

**Comment by cowtowncoder** [comment]
Ok thanks. Likely problem still then with 2.8.9. Just wanted to ask since there has been lots of work for this format module lately, including `Map` handling.

**Comment by coder-hub** [comment]
Yes. May I know why there's a difference in the behavior with a map vs a pojo containing a map?

**Comment by cowtowncoder** [comment]
Oh. Actually... I suspect your problem is Type Erasure -- type of `Map` you give will be `Map<Object,Object>`, regardless of what type parameters you are trying to use.
Instead, you need to use `JavaType` which can specify parameterization properly:

```java
JavaType t = mapper.getTypeFactory().constructType(new TypeReference<Map<String,Pojo>>() } };
// or one of other create methods from `TypeFactory`
```

Now: the reason why `Map` reached via property is different is that in such a case POJO class definition actually contains full generic type parameters, so:

```java
public class Pojo {
   public Map<String,String> stuff;
}
```

would be known as `Map<String,String>` (or whatever parameters are).
This is not true for `map.getClass()` -- there is always only just one `Class` object, and it is defined having type parameters (`K`, `V`). For more info you may want to read http://www.angelikalanger.com/GenericsFAQ/JavaGenericsFAQ.html which has great explanations on how Java generics work.

If this method still fails I'll have a look.

Actually, I may want to look into exception message too -- it should more clearly indicate the problem here, if any.

**Comment by cowtowncoder** [comment]
Ok: so, yes, untyped `Map`s can not be supported right now since there's the problem of how to represent type `java.lang.Object` for values.
But I improved error message, and converted it to a `JsonMappingException` for easier handling.
